clientes = [
    "Vinicius de Moraes",
    "Machado de Assis",
    "Fausto Silva",
    "Celso Portiolli",
    "Monteiro Lobato",
    "Clarice Lispector",
    "Neymar Junior",
    "Carlos Drummond de Andrade",
    "Gabriel Pato",
    "Filipe Deschamps",
    "Paulo Silveira",
    "Guilherme Silveira",
    "Vanessa Weber",
    "Gabriel Froes",
    "Ibere Thenorio",
    "Mariana Fulfaro",
    "Nilce Moretto",
    "Leon Martins",
]
